# Generated by Django 5.1.1 on 2024-10-04 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Learner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=200)),
                ("Last_Name", models.CharField(max_length=100)),
                ("Id_Proof", models.BigIntegerField()),
                ("Phone", models.BigIntegerField()),
                ("Date_of_Birth", models.DateField()),
                ("Email", models.EmailField(max_length=254)),
                (
                    "Registered_Date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("Batch_Id", models.IntegerField()),
                ("Alternate_Phone", models.BigIntegerField()),
                ("Description", models.TextField(max_length=300)),
                ("Exchange_Rate", models.BigIntegerField()),
                ("Source", models.CharField(max_length=20)),
                ("Learner_Owner", models.IntegerField()),
                ("Currency", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "Lead_created_time",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("Counselling_Done_BY", models.IntegerField()),
                ("Registered_Course", models.CharField(max_length=20)),
                (
                    "Preferable_Time",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("Tech_Stack", models.CharField(max_length=50)),
                ("Batch_Timing", models.DateField(default=django.utils.timezone.now)),
                ("Course_Commnets", models.CharField(max_length=100)),
                ("Mode_Of_Class", models.CharField(max_length=100)),
                ("Slack_Access", models.CharField(max_length=100)),
                ("Comment", models.CharField(max_length=100)),
                ("LMS_Access", models.CharField(max_length=100)),
                (
                    "Learner_Stage",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Advanced Discussion", "Advanced Discussion"),
                            ("Call not answered", "Call not answered"),
                            ("Ready to join", "Ready to join"),
                            ("Visiting", "Visiting"),
                            ("Fees Negotiation", "Fees Negotiation"),
                            ("Batch allocation", "Batch allocation"),
                            ("Need time this week", "Need time this week"),
                            ("Need time next week", "Need time next week"),
                            ("Need time this Month", "Need time this Month"),
                            ("Need time Next Month", "Need time Next Month"),
                            ("Special Requirment", "Speceial Requirement"),
                            ("Closed Won(Registered)", "Closed Won(Registered)"),
                            ("Closed Lost(Cold Lead)", "Closed Lost(Cold Lead)"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                (
                    "Attended_Demo",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Advanced Discussion", "Advanced Discussion"),
                            ("Call not answered", "Call not answered"),
                            ("Ready to join", "Ready to join"),
                            ("Visiting", "Visiting"),
                            ("Fees Negotiation", "Fees Negotiation"),
                            ("Batch allocation", "Batch allocation"),
                            ("Need time this week", "Need time this week"),
                            ("Need time next week", "Need time next week"),
                            ("Need time this Month", "Need time this Month"),
                            ("Need time Next Month", "Need time Next Month"),
                            ("Special Requirment", "Speceial Requirement"),
                            ("Closed Won(Registered)", "Closed Won(Registered)"),
                            ("Closed Lost(Cold Lead)", "Closed Lost(Cold Lead)"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
                (
                    "Location",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Advanced Discussion", "Advanced Discussion"),
                            ("Call not answered", "Call not answered"),
                            ("Ready to join", "Ready to join"),
                            ("Visiting", "Visiting"),
                            ("Fees Negotiation", "Fees Negotiation"),
                            ("Batch allocation", "Batch allocation"),
                            ("Need time this week", "Need time this week"),
                            ("Need time next week", "Need time next week"),
                            ("Need time this Month", "Need time this Month"),
                            ("Need time Next Month", "Need time Next Month"),
                            ("Special Requirment", "Speceial Requirement"),
                            ("Closed Won(Registered)", "Closed Won(Registered)"),
                            ("Closed Lost(Cold Lead)", "Closed Lost(Cold Lead)"),
                        ],
                        default="None",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
